In [33]:
import pandas as pd
import numpy as np
import seaborn as sns

In [64]:
df = pd.read_csv('wine_data.csv',header=None,usecols=[0,1,2])
df.columns=['Class label', 'Alcohol', 'Malic acid']

In [66]:
df

     Class label  Alcohol  Malic acid
0              1    14.23        1.71
1              1    13.20        1.78
2              1    13.16        2.36
3              1    14.37        1.95
4              1    13.24        2.59
..           ...      ...         ...
173            3    13.71        5.65
174            3    13.40        3.91
175            3    13.27        4.28
176            3    13.17        2.59
177            3    14.13        4.10

[178 rows x 3 columns]

In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,_y_test=train_test_split(df.drop('Class label', axis=1),df["Class label"],test_size=0.3,random_state=0)

In [84]:

X_train.shape, X_test.shape

((124, 2), (54, 2))

In [92]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
# Transform the data using the fitted transformer
X_train_scaled = scaler.transform(x_train)
# Transform the data using the fitted transformer
X_test_scaled = scaler.transform(x_test)

In [94]:
X_train_scaled

array([[0.72043011, 0.20378151],
       [0.31989247, 0.08403361],
       [0.60215054, 0.71218487],
       [0.57258065, 0.56302521],
       [0.76075269, 0.1302521 ],
       [0.48924731, 0.5       ],
       [0.75537634, 0.67857143],
       [0.61021505, 0.17436975],
       [0.54301075, 0.62394958],
       [0.39784946, 0.07352941],
       [0.33870968, 0.1092437 ],
       [0.46774194, 0.53361345],
       [0.5188172 , 0.53781513],
       [0.70967742, 0.07563025],
       [0.57258065, 0.30882353],
       [0.36021505, 0.0105042 ],
       [0.38709677, 0.13235294],
       [0.20967742, 0.25840336],
       [0.59408602, 0.64915966],
       [0.82526882, 0.26680672],
       [0.15591398, 0.09663866],
       [0.52688172, 0.16386555],
       [0.46774194, 0.31512605],
       [0.65860215, 0.16386555],
       [0.1155914 , 0.5987395 ],
       [0.27956989, 0.26680672],
       [0.21236559, 0.12184874],
       [0.65053763, 0.59033613],
       [0.31451613, 0.44957983],
       [0.54301075, 0.17647059],
       [0.57526882, 0.90336134],
       [0.28225806, 0.09243697],
       [0.30645161, 0.11764706],
       [0.37365591, 0.74369748],
       [0.22580645, 0.71848739],
       [0.3172043 , 0.06302521],
       [0.78225806, 0.17647059],
       [0.82526882, 0.23739496],
       [0.44086022, 0.01890756],
       [1.        , 0.17647059],
       [0.32795699, 0.80462185],
       [0.48924731, 0.14915966],
       [0.72580645, 0.7289916 ],
       [0.81451613, 0.15546218],
       [0.69892473, 0.19327731],
       [0.34946237, 0.0210084 ],
       [0.75      , 0.18067227],
       [0.28225806, 0.25      ],
       [0.53763441, 0.00210084],
       [0.89784946, 0.22268908],
       [0.57526882, 0.35714286],
       [0.45430108, 0.18067227],
       [0.90322581, 0.20588235],
       [0.62096774, 0.0105042 ],
       [0.16935484, 0.20798319],
       [0.21774194, 0.        ],
       [0.49193548, 0.09663866],
       [0.7311828 , 0.17647059],
       [0.40322581, 0.97058824],
       [0.55913978, 0.21218487],
       [0.90053763, 0.20588235],
       [0.86021505, 0.17226891],
       [0.26075269, 0.1302521 ],
       [0.59139785, 0.50630252],
       [0.90053763, 0.56722689],
       [0.83064516, 0.12394958],
       [0.26075269, 0.53361345],
       [0.35215054, 0.32773109],
       [0.65860215, 0.19327731],
       [0.60752688, 0.22689076],
       [0.63978495, 0.6197479 ],
       [0.72043011, 1.        ],
       [0.36021505, 0.06722689],
       [0.58333333, 0.18697479],
       [0.11290323, 0.31722689],
       [0.69623656, 0.85294118],
       [0.76612903, 0.21008403],
       [0.37365591, 0.3487395 ],
       [0.47849462, 0.29831933],
       [0.41666667, 0.08403361],
       [0.75268817, 0.14285714],
       [0.5483871 , 0.12815126],
       [0.44892473, 0.55882353],
       [0.73655914, 0.21218487],
       [0.48655914, 0.43487395],
       [0.36021505, 0.15546218],
       [0.66666667, 0.19117647],
       [0.76344086, 0.21218487],
       [0.28225806, 0.10504202],
       [0.68548387, 0.16176471],
       [0.55107527, 0.63235294],
       [0.20430108, 0.2605042 ],
       [0.38172043, 0.44957983],
       [0.71236559, 0.19747899],
       [0.66935484, 0.4789916 ],
       [0.66397849, 0.46848739],
       [0.49462366, 0.78151261],
       [0.80376344, 0.16596639],
       [0.33870968, 0.4789916 ],
       [0.28225806, 0.05042017],
       [0.44892473, 0.62605042],
       [0.        , 0.1302521 ],
       [0.6155914 , 0.49369748],
       [0.83333333, 0.67436975],
       [0.66129032, 0.16176471],
       [0.21774194, 0.42016807],
       [0.54301075, 0.24369748],
       [0.45430108, 0.19327731],
       [0.4811828 , 0.5210084 ],
       [0.63709677, 0.77941176],
       [0.85752688, 0.6512605 ],
       [0.72311828, 0.11344538],
       [0.51075269, 0.40336134],
       [0.16397849, 0.24579832],
       [0.33870968, 0.1512605 ],
       [0.16666667, 0.16386555],
       [0.60483871, 0.15756303],
       [0.51075269, 0.61134454],
       [0.76075269, 0.09663866],
       [0.21236559, 0.17436975],
       [0.36021505, 0.05882353],
       [0.37365591, 0.1512605 ],
       [0.77150538, 0.16596639],
       [0.84139785, 0.34033613]])

In [122]:
X_train_scaled = pd.DataFrame(X_train_scaled)
X_test_scaled = pd.DataFrame(X_test_scaled)

In [130]:
X_train_scaled
X_test_scaled

     Alcohol  Malic acid
0   0.728495    0.163866
1   0.473118    0.373950
2   0.360215    0.050420
3   0.680108    0.176471
4   0.543011    1.031513
5   0.142473    0.243697
6   0.814516    0.264706
7   0.357527    0.617647
8   0.327957    0.176471
9   0.282258    0.197479
10  0.626344    0.350840
11  0.766129    0.871849
12  0.852151    0.182773
13  0.360215    0.037815
14  0.685484    0.355042
15  0.260753    0.006303
16  0.733871    0.134454
17  0.849462    0.147059
18  0.432796    0.098739
19  0.752688    0.159664
20  0.559140    0.025210
21  0.543011    0.159664
22  0.594086    0.357143
23  0.397849    0.176471
24  0.349462    0.044118
25  0.400538    0.323529
26  0.376344    0.134454
27  0.303763    0.151261
28  0.196237    0.376050
29  0.739247    0.392857
30  0.634409    0.184874
31  0.857527    0.170168
32  0.271505    0.716387
33  0.854839    0.661765
34  1.021505    0.157563
35  0.543011    0.184874
36  0.715054    0.497899
37  0.446237    0.134454
38  0.158602    0.231092
39  0.637097    0.634454
40  0.663978    0.193277
41  0.725806    0.128151
42  0.338710    0.407563
43  0.422043    0.094538
44  0.102151   -0.031513
45  0.701613    0.464286
46  0.422043    0.329832
47  0.250000    0.042017
48  0.327957    0.628151
49  0.879032    0.216387
50  0.497312    0.441176
51  0.661290    0.567227
52  0.680108    0.172269
53  0.889785    0.165966